### ISSUE TITLE
Updating top-level tags dict in config file does not propagate to already deployed stacks

### ISSUE THREAD

**Issue by mchristen** [cloudtools/stacker#605]
Scenario:

I have a stack deployed from a config file like the following
```
namespace: test
tags:
  "tag1": "value1"
  "tag2": "value2"

stacks:
  - name: test-stack
    enabled: true
    classpath: TestBlueprint
    variables:
        Var1: "value1"
```

After deploying that stack all of the sub-resources of the stack contain the tags defined in the top-level.

Additionally, the actual CloudFormation Stack resource also has the same tags applied(as expected).

If I then go and change the top-level tags dict to something like
```
tags:
  "tag1": "value1"
  "tag2": "value2"
  "tag3": "value3"
```

and then re-deploy the stack none of the tags are updated.

Using 'interactive' mode it prompts me for the resource changes and every single one indicates that 'Tags' are being updated on the resources w/o replacement of the resource but after stacker finishes the deploy none of the actual tags are updated on any of the resources or on the stack itself.

If I then go and try to re-deploy the stack using the same config/env I go through the same process of having it prompt me for updates to the tags for all resources and then not apply them so I get stuck in this loop of not being able to update the tags. 

Any ideas?
