### ISSUE TITLE
Getting ImportError: No module named blueprints.kinesis when trying to build my stack

### ISSUE THREAD

**Issue by LamborghiniVeneno** [cloudtools/stacker#622]
I want to build a simple stack with Stacker and it is giving me this error:

> ImportError: No module named blueprints.kinesis when trying to build my stack_ error on build.

My directory structure is like this:

```
.
├── blueprints
│   ├── __init__.py
│   └── kinesis.py
└── conf
    └── example.yml
```

`__init__.py` is an empty file. `kinesis.py` has a simple blueprint definition:

```python
"""
An example.
"""

from stacker.blueprints.base import Blueprint
from stacker.blueprints.variables.types import TroposphereType
from troposphere.kinesis import Stream


class Kinesis(Blueprint):
    VARIABLES = {
        "Stream": {
            "type": TroposphereType(Stream, many=False),
            "description": "A Kinesis stream."
        }
    }

    def create_template(self):
        template = self.template
        variables = self.get_variables()

        template.add_resource(variables["Stream"])
```

And `example.yml` looks like this:

```
namespace: samples

stacker_bucket: "cloudformations-..."

stacks:
  - name: kinesis
    class_path: blueprints.kinesis.Kinesis
    variables:
      Stream:
        Name: nile
        RetentionPeriodHours: 24
        ShardCount: 1
```

I have created a venv and installed stacker in the venv:

```
pip install stacker==1.2.0
```

but when I run this command:

```
$ stacker build -d dump conf/example.yml
```

It gives me this error:

> ImportError: No module named blueprints.kinesis

I have attached my code to this issue. Any ideas what am I missing here? Looks like `blueprints.kinesis` is not added to the class path.

[code.zip](https://github.com/cloudtools/stacker/files/2169335/code.zip)
