### ISSUE TITLE
Raw CFN templates cannot be used in remote packages

### ISSUE THREAD

**Issue by troyready** [cloudtools/stacker#628]
"Remote" blueprints can be used because downloaded packages are added to the python syspath. Raw template cannot be accessed in this way.

**Comment by troyready** [comment]
One solution that we've come up with (credit to my colleague JR) is to add a new field to the package sources & stack definitions to indicate when/where template loading should be done relative to that package, e.g.:
 ```
package_sources:
  git:
   - uri: ssh://git@bitbucket..com/myorg/stacker-modules.git
     template_package_name: mystackermodules

stacks:
  mystack:
    template_package_name: mystackermodules
    template_path: cloudformation/ssm_parameter.yaml
```
In this case, because stack `mystack` has a defined template_package_name, its template loading will be done relative to that downloaded package's directory.
