### ISSUE TITLE
Package sources and conflicting file names for raw templates

### ISSUE THREAD

**Issue by kddejong** [cloudtools/stacker#667]
In the following scenario you would end up with two VPC stacks.  Is there way to force a certain raw package to be used when defining template_path?
```
package_sources:
  git:
    - uri: git@github.com:SomeUser/vpc.git
    - uri: git@github.com:SomeUser/config.git

stacks:
  - name: vpc
    template_path: cloudformation.yaml
  - name: config
    template_path: cloudformation.yaml
```
