### ISSUE TITLE
Regression: Locked stacks do not properly construct dependency list.

### ISSUE THREAD

**Issue by mromaszewicz** [cloudtools/stacker#745]
Consider this scenario:
Stack A has output Foo.
Stack B depends on A::Foo

This is expected to work:
stacks:
```
- name: A
   enabled: true
   class_path: <something>
- name: B
   enabled: true
   locked: true
   class_path: <something>
   variables:
     SomeInput: ${output A::Foo}
  ```

It is expected that stack A must be in the dependency DAG before stack B, but this doesn't happen as of stacker 1.5.0. It works properly in stacker 1.4.1

In stacker 1.5.0, dependencies are built correctly if stack B is not locked. However, at creation time, it should not matter whether a stack is locked or not.

This is easiest to reproduce by having a stacker file with 2 stacks in it, and swap their order if it works initially. It will fail in 1.5.0+
