### ISSUE TITLE
Can't add stack description with latest version of troposphere

### ISSUE THREAD

**Issue by JulioPablo** [cloudtools/stacker#771]
If I have a stacker definition that includes a description, like
```
stacks:
- name: myStack
  class_path: ...
  stack_name: ...
  description: My lovely stack
  region: ...
```

I get the following error when trying to build the stack

```
AttributeError: `Template` object has no attribute `add_description`
```

I believe this has to do with some changes made on the 3.0.0 troposphere release 

Stacker 1.7.2
troposphere 3.0.3
Python 3.9.7
Windows 10
